#!/usr/bin/env bash
set -euo pipefail

cd /home/jovyan/LATeachingSuite

PYTHON_EXE="$(command -v python3)"

julia --project=. -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/ea42gh/GenLAProblems.jl.git", rev="a03b85fd4145d55c49e1bec4e3688e1cb8acffaa")); Pkg.add(PackageSpec(url="https://github.com/ea42gh/LAlatex.git", rev="a36ed42edfb25f26b50fdf4907f7dc3e2a33d421")); Pkg.instantiate(); Pkg.precompile()'
JULIA_PYTHONCALL_EXE="$PYTHON_EXE" JULIA_CONDAPKG_BACKEND=Null CONDAPKG_BACKEND=Null julia --project=. -e 'using LATeachingSuite, LinearAlgebra, LaTeXStrings, Random; Random.seed!(42)'
JULIA_PYTHONCALL_EXE="$PYTHON_EXE" JULIA_CONDAPKG_BACKEND=Null CONDAPKG_BACKEND=Null julia --project=. binder/notebook_warmup.jl
julia -e "using Pkg; Pkg.add(\"IJulia\"); Pkg.precompile(); using IJulia; installkernel(\"Julia 1.10\", \"--project=/home/jovyan/LATeachingSuite\"; specname=\"julia-1.10\", displayname=\"Julia 1.10\", env=Dict(\"JULIA_PROJECT\"=>\"/home/jovyan/LATeachingSuite\", \"JULIA_PYTHONCALL_EXE\"=>\"$PYTHON_EXE\", \"JULIA_CONDAPKG_BACKEND\"=>\"Null\", \"CONDAPKG_BACKEND\"=>\"Null\", \"PYTHONNOUSERSITE\"=>\"1\", \"PYTHONDONTWRITEBYTECODE\"=>\"1\", \"ENABLE_JULIACALL_AUTACTIVATE\"=>\"0\"))"
jupyter trust /home/jovyan/work/LATeachingSuite_demo.ipynb
jupyter nbconvert --to notebook --execute --inplace /home/jovyan/work/LATeachingSuite_demo.ipynb
